Auth
rociac/members-only pull request #1
Opened 2019-10-01 21:50 UTC by rociac

Looking forward for your feedback!

2019-10-02 00:16 UTC, efrapp requested changes
### Hi @rociac and @onedebos 👋 
You are doing a good job so far. Please see my suggestion bellow.
Also, I wasn't able to test your app in the browser because you have some errors related to Sass, please fix those errors and send a new code review with the app completely functional.

**Required changes**
- [X] Please check this issue: #2
- [X] Check this issue also: #3. There are a lot of Sass undefined variables you are using in your project. (Maybe this is related to the issue #2)
- [ ] It uses the #current_user=(user) method to set user

**Status:** `Changes required`

2019-10-02 00:16 UTC, efrapp commented on app/models/user.rb
> +      SecureRandom.urlsafe_base64
You missed step 5.2 in the Odin project, about encrypting the token.

2019-10-02 00:16 UTC, efrapp commented on config/routes.rb
> +  get 'microposts/index'
It is better to use the `:resources` method.

2019-10-02 00:16 UTC, efrapp commented on app/controllers/microposts_controller.rb
> +  def user_params
Maybe a more accurate name should be `micropost_params`

2019-10-02 00:16 UTC, efrapp commented on app/controllers/microposts_controller.rb
> +    @micropost.user = current_user
These lines could be refactored using the `build` method from the association between users and microposts.

2019-10-02 00:16 UTC, efrapp commented on app/controllers/application_controller.rb
> +  end
For this method, you should generate the remember token and update the signed-in user with that token.

2019-10-08 15:34 UTC, rociac commented on app/models/user.rb
> +      SecureRandom.urlsafe_base64
Hi, thank you for reviewing our code. We did encrypt the password using our digest method declared above inside class << self it uses the remember_token and the authenticated method to encrypt the password.

2019-10-08 15:46 UTC, rociac commented on app/controllers/application_controller.rb
> +  end
We did generate the remember token but it's split in different methods, we use the remember method and the current_user? method to achieve that.

2019-10-09 10:27 UTC, SunnyAsar requested changes
# Hi @rociac  and @onedebos 👋 
- your code looks good, and i see some updates from the previous review. There are still a few left.
- I'm unable to use the app generally please look into the sass issue.
![Screenshot 2019-10-09 at 11 26 43 AM](https://user-images.githubusercontent.com/10922508/66473703-b9312100-ea87-11e9-8ea8-294e82a04d1d.png)
### please fix this so we can move forward.
**Request another review when everything is in place**

2019-10-09 10:27 UTC, SunnyAsar commented on config/routes.rb
> +  get 'microposts/index'
Hi, please update this as suggested previously, use the resources with only flag to specify the methods you want.

2019-10-11 01:43 UTC, efrapp requested changes
### Great job team! 👷

Thanks for solving the problem with Sass, I was able to review the app without problems.
Please address the following suggestions:

- [ ] As a guest you can see only post's text: you need to allow to check all the posts even is no user is signed-in but without the author's name.
- [ ] It uses the #current_user=(user) method to set user
- [ ] the author is displayed only if a user is signed in (uses ApplicationController#signed_in? helper method)

**Status:** `Changes required`

2019-10-11 01:43 UTC, efrapp commented on config/routes.rb
> +  resources :microposts, only: [:new, :create, :index]
Nice guys! 👍

2019-10-16 17:54 UTC, Oghenebrume50 approved these changes
looks good Team, all the changes work fine **This is approved**

2019-11-07 20:26 UTC, merged